In [7]:
import pandas as pd
import sqlite3

In [6]:
df = pd.read_csv("Churn_Modelling.csv")

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [8]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [9]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
20,21,15577657,McDonald,732,France,Male,41,8,0.0,2,1,1,170886.17,0
21,22,15597945,Dellucci,636,Spain,Female,32,8,0.0,2,1,0,138555.46,0
22,23,15699309,Gerasimov,510,Spain,Female,38,4,0.0,1,1,0,118913.53,1
23,24,15725737,Mosman,669,France,Male,46,3,0.0,2,0,1,8487.75,0
24,25,15625047,Yen,846,France,Female,38,5,0.0,1,1,1,187616.16,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        25 non-null     int64
 1   CustomerId       25 non-null     int64
 2   Surname          25 non-null     object
 3   CreditScore      25 non-null     int64
 4   Geography        25 non-null     object
 5   Gender           25 non-null     object
 6   Age              25 non-null     int64
 7   Tenure           25 non-null     int64
 8   Balance          25 non-null     float64
 9   NumOfProducts    25 non-null     int64
 10  HasCrCard        25 non-null     int64
 11  IsActiveMember   25 non-null     int64
 12  EstimatedSalary  25 non-null     float64
 13  Exited           25 non-null     int64
dtypes: float64(2), int64(9), object(3)
memory usage: 2.9+ KB

In [11]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 25
Columns : 14

In [12]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [13]:
df.describe(include='all')

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,25.000000,2.500000e+01,25,25.000000,25,25,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.00000
unique,NaN,NaN,25,NaN,3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Hargrave,NaN,France,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,1,NaN,13,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,13.000000,1.566413e+07,NaN,620.600000,NaN,NaN,37.640000,4.920000,50087.438400,1.800000,0.680000,0.520000,91516.287200,0.24000
std,7.359801,6.934289e+04,NaN,118.825152,NaN,NaN,8.943713,2.722132,64063.546275,0.707107,0.476095,0.509902,55233.205635,0.43589
min,1.000000,1.556898e+07,NaN,376.000000,NaN,NaN,24.000000,1.000000,0.000000,1.000000,0.000000,0.000000,5097.670000,0.00000
25%,7.000000,1.560088e+07,NaN,528.000000,NaN,NaN,31.000000,3.000000,0.000000,1.000000,0.000000,0.000000,64327.260000,0.00000
50%,13.000000,1.564731e+07,NaN,619.000000,NaN,NaN,39.000000,5.000000,0.000000,2.000000,1.000000,1.000000,80181.120000,0.00000
75%,19.000000,1.572574e+07,NaN,684.000000,NaN,NaN,44.000000,7.000000,115046.740000,2.000000,1.000000,1.000000,119346.880000,0.00000
max,25.000000,1.579236e+07,NaN,850.000000,NaN,NaN,58.000000,10.000000,159660.800000,4.000000,1.000000,1.000000,190857.790000,1.00000

In [14]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [15]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [16]:
df = df.drop_duplicates()

print("Duplicates Removed Successfully!")

Duplicates Removed Successfully!

In [17]:
df.to_excel("Churn_Modelling.xlsx", index=False)

print("Excel File Exported Successfully!")

Excel File Exported Successfully!

In [18]:
excel_df = pd.read_excel("Churn_Modelling.xlsx")

excel_df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [19]:
conn = sqlite3.connect("ChurnDatabase.db")

df.to_sql("CustomerData", conn, if_exists="replace", index=False)

print("Database Created Successfully!")

Database Created Successfully!

In [20]:
query = "SELECT * FROM CustomerData LIMIT 5"

sql_df = pd.read_sql(query, conn)

sql_df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [21]:
df.to_csv("Churn_Output.csv", index=False)

print("CSV File Exported Successfully!")

CSV File Exported Successfully!

In [22]:
df.to_json("Churn_Output.json", orient="records", indent=4)

print("JSON File Exported Successfully!")

JSON File Exported Successfully!

In [23]:
import os

files = [
    "Churn_Modelling_Export.csv",
    "Churn_Modelling_Export.xlsx",
    "Churn_Modelling_Export.json"
]

for file in files:
    if os.path.exists(file):
        print(file, "Created Successfully")
    else:
        print(file, "Not Found")

Churn_Modelling_Export.csv Not Found
Churn_Modelling_Export.xlsx Not Found
Churn_Modelling_Export.json Not Found